from . import student
from . import vaccine
from . import vaccine_type
from . import parent
from . import parent_contact
from . import grade
from . import grade_group
from . import class_type
from . import generate_class_name
from . import class_name